---
trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

variables:
  # Differentiate between branches
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  # Configure SonarCloud
  cliProjectKey: #TODO: Add as part of SonarCloud setup
  cliProjectName: #TODO: Add as part of SonarCloud setup
  solution: "**/**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dockerRegistryServiceConnection: "FontysServiceConnection"
  dockerRepository: "fontyssa/Route-Coordinator-Service"
  dockerFile: "**/**/Dockerfile"

resources:
  repositories:
    - repository: templates
      endpoint: Groep2Rekeningrijden
      type: github
      name: Groep2Rekeningrijden/Templates

stages:
  - stage: Build
    displayName: "Build Stage"

    jobs:
      - job: BuildJob
        displayName: "Build Job"

        steps:
          - task: UseDotNet@2
            inputs:
              version: "7.x"
              includePreviewVersions: true

          - task: NuGetToolInstaller@1

          - task: NuGetCommand@2
            inputs:
              restoreSolution: "$(solution)"

          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              projects: "$(solution)"
              arguments: "--configuration $(buildConfiguration)"
  # - stage: SonarCloudAnalysis
  #   displayName: 'SonarCloud Analysis'
  #   jobs:
  #     - job: SonarCloudJob
  #       displayName: 'Run SonarCloud Analysis'
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #         - script: |
  #             # Run SonarCloud Analysis
  #             sonarcloud:
  #               organization: 'FontysVerkeer'
  #               projectKey: 'fontysverkeer'
  #           displayName: 'Run SonarCloud Analysis'
  - stage: DockerBuildAndPush
    displayName: "Build and push Docker Image"
    jobs:
      - job: BuildJob
        displayName: "Build and Tag"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: "Build and Tag Docker Image"
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(dockerRepository)"
              command: "buildAndPush"
              Dockerfile: "$(dockerFile)"
              tags: |
                latest
                $(Build.BuildId)











  # - stage: test_isolated
  #   jobs:
  #     # --- Run linters on isolated environment ---
  #     - job: linting
  #       steps:
  #         - template: #TODO: Set install template, example "install/python-3_11.yml@templates"
  #         - template: #TODO: Set linting template, example "lint/python.yml@templates"
  #         - template: lint/fail_if_linters_fail.yml@templates

  #     # --- Run unit tests on isolated instance ---
  #     - job: unit_test
  #       steps:
  #         - checkout: self
  #           fetchDepth: 0
  #         - template: #TODO: Set install template, example "install/python-3_11.yml@templates"
  #         - template: test/sonar_cloud_prepare.yml@templates
  #         - template: #TODO: Set unit test template, example "test/python_pytest.yml@templates"
  #         - template: test/sonar_cloud_analyze.yml@templates

  # # --- Run tests on dev environment ---
  # - stage: test_dev
  #   dependsOn: test_isolated
  #   condition: and(succeeded(), or(eq(variables.isDev, 'true'), eq(variables.isMain, 'true')))
  #   jobs:
  #     - job: B1
  #     - job: B2

  # # --- Deploy to prod ---
  # - stage: prod
  #   dependsOn: test_dev
  #   condition: and(succeeded(), eq(variables.isMain, 'true'))
  #   jobs:
  #     - job: C1
  #     - job: C2
